### ISSUE TITLE
generic approach to checking predicates approximately

### ISSUE THREAD

**Issue by jlapeyre** [iitis/QuantumInformation.jl#84]
You may be interested in this attempt to make a uniform, flexible, and performant interface for choosing different definitions of approximate equality [IsApprox.j](https://github.com/jlapeyre/IsApprox.jl). I noticed that QI packages tend to repeat and reimplement some parts of this.

If the package turns out to be useful, you could depend on it, rather that rolling your own. Or perhaps just take ideas from it.

**Comment by pgawron** [comment]
@jlapeyre Thanks for the information. I'm personally very keen on reusing other people's work. When do you plan to register your package?

**Comment by jlapeyre** [comment]
Good. I'll register it soon. Today if possible.

**Comment by jlapeyre** [comment]
`IsApprox.jl` is now registered.
