### ISSUE TITLE
partial trace for non-numeric matrices

### ISSUE THREAD

**Issue by lkapelevich** [iitis/QuantumInformation.jl#93]
Thanks for this package!
Would it be OK to remove the `<:Number` restriction in https://github.com/iitis/QuantumInformation.jl/blob/master/src/ptrace.jl#L11? My use case is to calculate `ptrace` with [JuMP variables](https://jump.dev/JuMP.jl/stable/manual/variables/) and things seem to work with just `ρ::AbstractMatrix`

**Comment by lpawela** [comment]
@lkapelevich we will try to implement this in some reasonable timeframe.

**Comment by lpawela** [comment]
@lkapelevich I removed the requirement, you can see it here a213dd3. Is this sufficient for your use case?

**Comment by lkapelevich** [comment]
Yep that's what I had in mind!
